
const SID="1TSpt_DxEDhpsXE09lNx8S63b7cDomEXhVua--p99DGM";
function clean(v){return String(v??"").trim()}
function parseCSV(text){const rows=[];let row=[],field="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c=='"'&&text[i+1]=='"'){field+='"';i++}else if(c=='"')q=false;else field+=c}else if(c=='"')q=true;else if(c==','){row.push(field);field=""}else if(c=='\n'){row.push(field);rows.push(row);row=[];field=""}else if(c!='\r')field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
async function sheet(tab,header){const u=`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}&headers=0`;const c=new AbortController(),tm=setTimeout(()=>c.abort(),10000);try{const r=await fetch(u,{signal:c.signal,cache:"no-store"});if(!r.ok)throw new Error(`${tab} HTTP ${r.status}`);const raw=await r.text();if(/<html|accounts\.google\.com|sign in/i.test(raw))throw new Error(`${tab} is not anonymously readable`);const rows=parseCSV(raw),hi=rows.findIndex(r=>clean(r[0]).toLowerCase()===header.toLowerCase());if(hi<0)throw new Error(`${tab} header missing`);const heads=rows[hi].map(clean);return rows.slice(hi+1).filter(r=>r.some(x=>clean(x))).map((r,n)=>({...Object.fromEntries(heads.map((h,i)=>[h,clean(r[i])])),_row:hi+n+2}))}finally{clearTimeout(tm)}}
function json(body,status=200){return Response.json(body,{status,headers:{"cache-control":"no-store"}})}

function norm(v){v=clean(v);if(!v)return"";return /^https?:\/\//i.test(v)?v:"https://"+v}
function displayDate(v){const d=new Date(`${clean(v)}T00:00:00`);return Number.isNaN(d.getTime())?clean(v):new Intl.DateTimeFormat("en-US",{year:"numeric",month:"long",day:"numeric"}).format(d)}
export default async req=>{if(req.method!=="GET")return json({error:"Method not allowed"},405);try{const [p,b]=await Promise.all([sheet("Publications","title"),sheet("The Bulletin","message")]);return json({publications:p.filter(x=>clean(x.published).toLowerCase()==="yes"&&x.title).map(x=>({title:x.title,date:x.date,date_display:displayDate(x.date),body:x.body||"",photo_url:norm(x.photo_url)})),bulletin:b.filter(x=>clean(x.published).toLowerCase()==="yes"&&x.message).map(x=>({message:x.message,link:norm(x.link)}))})}catch(e){return json({error:e.message},502)}};
