const clean=v=>String(Array.isArray(v)?v[0]||"":v||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const asHttps=v=>{try{const u=new URL(String(v||""));if(!/^https?:$/.test(u.protocol))return"";u.protocol="https:";return u.href}catch{return""}};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const out=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":status===200?"public, max-age=300, s-maxage=1800":"no-store"}});
async function j(url,headers={},ms=16000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json",...headers}});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d?.error||d?.message||`HTTP ${r.status}`),{status:r.status});return d}finally{clearTimeout(t)}}
function walk(o,fn,depth=0){if(o==null||depth>12)return;if(Array.isArray(o)){for(const x of o)walk(x,fn,depth+1);return}if(typeof o!=="object")return;fn(o);for(const x of Object.values(o))walk(x,fn,depth+1)}
function nyplImages(node){const found=[];walk(node,o=>{const links=o?.imageLinks?.imageLink||o?.imageLinks;if(!links)return;const arr=Array.isArray(links)?links:[links];for(const l of arr){const url=asHttps(typeof l==="string"?l:l?.url||l?.href||l?.value);if(url)found.push(url)}});return [...new Set(found)]}
function pickNYPLTitle(node){let title="";walk(node,o=>{if(title)return;for(const k of ["title","name","label","display"]){if(typeof o?.[k]==="string"&&o[k].trim()){title=clean(o[k]);break}}});return title||"NYPL public-domain discovery"}
function pickNYPLId(node){let id="";walk(node,o=>{if(id)return;for(const k of ["uuid","captureUuid","itemUuid","id"]){const v=o?.[k];if(typeof v==="string"&&v.length>6){id=clean(v);break}}});return id}
async function nypl(seed){const token=Netlify.env.get("NYPL_API_TOKEN");if(!token)return out({error:"PARKED: NYPL adapter is finished, but NYPL_API_TOKEN is not configured yet."},503);const terms=["flowers","maps","fashion","architecture","birds","menus","photography","theater","prints","New York"],q=terms[seed%terms.length],url=`https://api.repo.nypl.org/api/v2/items/search?q=${encodeURIComponent(q)}&publicDomainOnly=true&per_page=40&page=${1+(seed%5)}`;let data;try{data=await j(url,{Authorization:`Token token=\"${token}\"`})}catch(e){return out({error:e.status===401?"PARKED: NYPL_API_TOKEN was rejected. Replace it later and retest.":`NYPL request failed (${e.message}).`},e.status===401?503:502)}const candidates=[];walk(data,o=>{const imgs=nyplImages(o);if(!imgs.length)return;const id=pickNYPLId(o)||String(hash(JSON.stringify(imgs)));candidates.push({id:`nypl:${id}`,title:pickNYPLTitle(o),creator:"New York Public Library",image:imgs.at(-1),thumbnail:imgs[0],sourceURL:"https://digitalcollections.nypl.org/",rightsLabel:"Public domain / no known U.S. copyright restrictions · NYPL"})});const uniq=[...new Map(candidates.map(x=>[x.id,x])).values()];if(uniq.length<2)return out({error:"NYPL authenticated successfully but this search did not expose two eligible image captures."},503);return out({source:"New York Public Library",items:uniq.slice(0,12)});}

function safeBHLRights(x){const s=`${x?.CopyrightStatus||""} ${x?.LicenseUrl||""} ${x?.Rights||""}`.toLowerCase();return /public domain|out of copyright|not in copyright|creativecommons\.org\/publicdomain\/(zero|mark)/.test(s)&&!/permission to digitize|noncommercial|non-commercial|copyrighted/.test(s)}
async function bhl(seed){const key=Netlify.env.get("BHL_API_KEY");if(!key)return out({error:"PARKED: Biodiversity Heritage Library adapter is finished, but BHL_API_KEY is not configured yet."},503);const terms=["botanical","birds","insects","flowers","shells","fishes","fungi","butterflies"],term=terms[seed%terms.length],search=`https://www.biodiversitylibrary.org/api3?op=PublicationSearch&searchterm=${encodeURIComponent(term)}&searchtype=F&format=json&apikey=${encodeURIComponent(key)}`;let data;try{data=await j(search)}catch(e){return out({error:e.status===401||e.status===403?"PARKED: BHL_API_KEY was rejected. Replace it later and retest.":`BHL search failed (${e.message}).`},e.status===401||e.status===403?503:502)}const pubs=Array.isArray(data?.Result)?data.Result:[];const ids=[];walk(pubs,o=>{const id=o?.ItemID||o?.ItemId||o?.itemid;if(id&&!ids.includes(String(id)))ids.push(String(id))});const start=ids.length?seed%ids.length:0,ordered=ids.slice(start).concat(ids.slice(0,start)),items=[];for(const id of ordered.slice(0,8)){let meta;try{meta=await j(`https://www.biodiversitylibrary.org/api3?op=GetItemMetadata&id=${encodeURIComponent(id)}&pages=t&format=json&apikey=${encodeURIComponent(key)}`)}catch{continue}const item=Array.isArray(meta?.Result)?meta.Result[0]:meta?.Result;if(!item||!safeBHLRights(item))continue;for(const p of item?.Pages||[]){const types=(p?.PageTypes||[]).map(x=>clean(x?.PageTypeName||x)).join(" ");if(types&&!/illustration|map|plate/i.test(types))continue;const image=asHttps(p?.FullSizeImageUrl||p?.ThumbnailUrl);if(!image)continue;items.push({id:`bhl:${p?.PageID||hash(image)}`,title:clean(p?.PageTitle)||clean(item?.Title)||`${term} illustration`,creator:"Biodiversity Heritage Library",image,thumbnail:asHttps(p?.ThumbnailUrl)||image,sourceURL:asHttps(p?.PageUrl)||asHttps(item?.ItemUrl)||"https://www.biodiversitylibrary.org/",rightsLabel:"Public-domain item · Biodiversity Heritage Library"});if(items.length>=12)break}if(items.length>=12)break}if(items.length<2)return out({error:"BHL authenticated successfully but this sample did not yield two conservatively public-domain illustration pages."},503);return out({source:"Biodiversity Heritage Library",items});}

export default async request=>{if(request.method!=="GET")return out({error:"Method not allowed"},405);const u=new URL(request.url),source=(u.searchParams.get("source")||"").toLowerCase(),seed=Math.abs(parseInt(u.searchParams.get("seed")||"1",10)||1);try{if(source==="nypl")return await nypl(seed);if(source==="bhl")return await bhl(seed);return out({error:"Unknown credential-world source."},400)}catch(e){return out({error:e?.message||"Credential-world source failed."},502)}};