import { getStore, getDeployStore } from "@netlify/blobs";
import { collectSource } from "./_daily-source-adapters.mjs";

const SID="1TSpt_DxEDhpsXE09lNx8S63b7cDomEXhVua--p99DGM";
const TZ="Asia/Manila";
const STORE_NAME="barbph-daily-discover";
const ENGINE_VERSION="2026-08-30-continuous-v1";
const BACKOFF_SECONDS=[30,60,120,300];
const READY_STATES=new Set(["PRODUCTION_READY","PRODUCTION"]);

function clean(v){return String(v??"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function nowISO(){return new Date().toISOString()}
function dateManila(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value;return`${g("year")}-${g("month")}-${g("day")}`}
function addDays(date,n){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function prod(){return Netlify.context?.deploy?.context==="production"}
function store(){return prod()?getStore(STORE_NAME,{consistency:"strong"}):getDeployStore(STORE_NAME,{consistency:"strong"})}
function json(body,status=200,lab=false){return Response.json(body,{status,headers:{"cache-control":lab||status!==200?"no-store":"public, max-age=30, s-maxage=60, stale-while-revalidate=300"}})}
async function getText(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=""}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=""}else if(c!=='\r')field+=c}if(field||row.length){row.push(field);rows.push(row)}return rows}
function table(raw,header){const rows=parseCSV(raw),i=rows.findIndex(r=>clean(r[0]).toLowerCase()===header.toLowerCase());if(i<0)throw new Error(`${header} header not found`);const heads=rows[i].map(clean);return rows.slice(i+1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(heads.map((h,j)=>[h,clean(r[j])]))) }
async function themeRows(){const urls=[`https://docs.google.com/spreadsheets/d/${SID}/export?format=csv&gid=342757810`,`https://docs.google.com/spreadsheets/d/${SID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent("Theme Sources")}&headers=0`];let last="";for(const u of urls){try{const raw=await getText(u);if(/<html|accounts\.google\.com|sign in/i.test(raw)){last="Theme Sources is not anonymously readable";continue}return table(raw,"source_name")}catch(e){last=e.message}}throw new Error(last||"Theme Sources unavailable")}
function rowConfig(r){return{source_name:clean(r.source_name),enabled:clean(r.enabled).toLowerCase()==="yes",weight:Number(r.weight)||0,adapter_key:clean(r.adapter_key),status:clean(r.production_status).toUpperCase(),mode:clean(r.operating_mode).toUpperCase()||"CONTINUOUS_DISCOVERY",batch_size:Math.max(12,Math.min(60,Number(r.stream_batch_size)||30)),rotation_seconds:Math.max(8,Math.min(120,Number(r.rotation_seconds)||18)),refresh_seconds:Math.max(60,Math.min(3600,Number(r.refresh_seconds)||600)),rights_rule:clean(r.rights_rule),country_region:clean(r.country_region)}}
function eligible(rows){return rows.map(rowConfig).filter(r=>r.enabled&&r.weight>0&&r.adapter_key&&READY_STATES.has(r.status))}
function weightedChoice(rows,date,last=""){const reduced=last&&rows.length>1?rows.filter(r=>r.source_name!==last):rows,total=reduced.reduce((n,r)=>n+r.weight,0);let p=(hash(`${ENGINE_VERSION}|${date}|${last}`)/4294967296)*total;for(const r of reduced){p-=r.weight;if(p<0)return r}return reduced.at(-1)}
async function getJSONBlob(s,key,fallback=null){return await s.get(key,{type:"json"}).catch(()=>fallback)??fallback}
async function event(s,date,type,data={}){const key=`continuous/events/${date}`,doc=await getJSONBlob(s,key,{version:1,events:[]});const events=Array.isArray(doc.events)?doc.events:[];events.push({at:nowISO(),type,...data});await s.setJSON(key,{version:1,updated_at:nowISO(),events:events.slice(-500)}).catch(()=>{})}
async function readHistory(s){return await getJSONBlob(s,"continuous/history/days",{days:[]})}
async function writeHistory(s,row){const h=await readHistory(s),days=(Array.isArray(h.days)?h.days:[]).filter(x=>x.date_manila!==row.date_manila);days.push(row);days.sort((a,b)=>String(a.date_manila).localeCompare(String(b.date_manila)));await s.setJSON("continuous/history/days",{version:1,updated_at:nowISO(),days:days.slice(-400)})}
async function selectControl(s,rows,date,forced=""){const key=`continuous/day/${date}/control`;let c=await getJSONBlob(s,key,null);if(c?.date_manila===date&&!forced)return c;const pool=eligible(rows);let chosen;if(forced){chosen=rows.map(rowConfig).find(r=>r.source_name===forced);if(!chosen)throw new Error(`Forced source not found: ${forced}`)}else{const h=await readHistory(s),y=(h.days||[]).find(x=>x.date_manila===addDays(date,-1));chosen=weightedChoice(pool,date,y?.scheduled_source||"")}if(!chosen)throw new Error("No enabled production-ready source is weighted above zero");c={version:1,date_manila:date,scheduled_source:chosen.source_name,adapter_key:chosen.adapter_key,operating_mode:chosen.mode,batch_size:chosen.batch_size,rotation_seconds:chosen.rotation_seconds,refresh_seconds:chosen.refresh_seconds,rights_rule:chosen.rights_rule,country_region:chosen.country_region,selected_at:nowISO(),locked_until:"next Manila day"};if(!forced){await s.setJSON(key,c);await event(s,date,"source_selected",{scheduled_source:c.scheduled_source,adapter_key:c.adapter_key})}return c}
function uniqueNew(items,seenIds,count){const out=[];for(const x of items||[]){if(!x?.id||!x?.image||seenIds.has(String(x.id)))continue;seenIds.add(String(x.id));out.push(x);if(out.length>=count)break}return out}
async function reserve(origin,seed,count){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(new URL(`/.netlify/functions/barb-reserve?seed=${seed}&count=${Math.min(12,count)}`,origin),{signal:c.signal,cache:"no-store"});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`Barb Originals HTTP ${r.status}`);return Array.isArray(d?.items)?d.items:[]}finally{clearTimeout(t)}}
function responseRecord({date,control,served,mode,assets,generation,health,reason=null,hold=false,cacheHit=false,refreshDueAt=null}){return{version:3,engine_version:ENGINE_VERSION,date_manila:date,scheduled_source:control.scheduled_source,served_source:served,service_mode:mode,fallback_used:mode!=="primary",fallback_reason:reason,daily_settings:{rotation_seconds:control.rotation_seconds,stream_batch_size:control.batch_size,refresh_seconds:control.refresh_seconds},stream:{continuous:true,generation,has_more:true,hold_last_asset:hold,refresh_due_at:refreshDueAt,next_retry_at:health?.next_retry_at||null,source_health:health?.state||"unknown"},assets,cache_hit:cacheHit,locked_until:"next Manila day"}}
async function compatibility(s,result){const day={...result,daily_set_id:`${result.date_manila}:${result.stream.generation}:${hash(result.assets.map(x=>x.id).join("|"))}`};await s.setJSON(`day/${result.date_manila}`,day).catch(()=>{});await writeHistory(s,{date_manila:result.date_manila,scheduled_source:result.scheduled_source,served_source:result.served_source,service_mode:result.service_mode,daily_set_id:day.daily_set_id,stream:result.stream,assets:result.assets.slice(0,60).map(a=>({id:a.id,family:a.family,title:a.title,sourceURL:a.sourceURL}))}).catch(()=>{});return result}
async function serveReserve({s,origin,date,control,state,health,reason,eventType="barb_originals_engaged"}){const reserveAssets=await reserve(origin,hash(`${date}|reserve|${health?.failures||0}|${reason}`),control.batch_size);if(!reserveAssets.length)throw new Error("Barb Originals returned no eligible assets");const generation=state?.generation||1,refreshDue=health?.next_retry_at?Date.parse(health.next_retry_at):Date.now()+300000,nextState={scheduled_source:control.scheduled_source,served_source:"Barb Originals",service_mode:"barb_reserve",generation,assets:reserveAssets,refresh_due_at:refreshDue,fallback_reason:reason,hold_last_asset:false,updated_at:nowISO()};const transition=state?.service_mode!=="barb_reserve";await s.setJSON(`continuous/day/${date}/stream`,nextState);if(transition)await event(s,date,eventType,{scheduled_source:control.scheduled_source,error:reason});const result=responseRecord({date,control,served:"Barb Originals",mode:"barb_reserve",assets:reserveAssets,generation,health,reason,refreshDueAt:refreshDue});await compatibility(s,result);return result}

export default async request=>{
  if(request.method!=="GET")return json({error:"Method not allowed"},405);
  const url=new URL(request.url),lab=url.searchParams.get("lab")==="1",forced=lab?clean(url.searchParams.get("force_source")):"",forceFail=lab&&url.searchParams.get("force_fail")==="1",resync=url.searchParams.get("resync")==="1",date=dateManila(),origin=url.origin,s=store(),now=Date.now();
  let rows;try{rows=await themeRows()}catch(e){return json({status:"CONTROL_UNAVAILABLE",date_manila:date,error:e.message},503,lab)}
  let control;try{control=await selectControl(s,rows,date,forced)}catch(e){return json({status:"NOT_ARMED",date_manila:date,error:e.message},503,lab)}
  const stateKey=`continuous/day/${date}/stream`,seenKey=`continuous/day/${date}/seen`,cacheKey=`continuous/day/${date}/last-known-good`,healthKey=`continuous/day/${date}/health`;
  let state=await getJSONBlob(s,stateKey,null),health=await getJSONBlob(s,healthKey,{state:"unknown",failures:0,next_retry_at:null,last_success_at:null,last_failure_at:null}),seenDoc=await getJSONBlob(s,seenKey,{ids:[]}),lastGood=await getJSONBlob(s,cacheKey,{assets:[]});
  if(state?.scheduled_source!==control.scheduled_source){state=null;health={state:"unknown",failures:0,next_retry_at:null,last_success_at:null,last_failure_at:null};seenDoc={ids:[]};lastGood={assets:[]}}

  const currentConfig=rows.map(rowConfig).find(r=>r.source_name===control.scheduled_source),manualHold=!lab&&(!currentConfig?.enabled||!READY_STATES.has(currentConfig?.status||""));
  if(manualHold){const reason=`Admin hold: ${control.scheduled_source} is disabled or not production-ready`;const firstHold=health.state!=="held";health={...health,state:"held",next_retry_at:null,last_failure_at:nowISO(),last_error:reason};await s.setJSON(healthKey,health);if(firstHold)await event(s,date,"admin_hold_engaged",{scheduled_source:control.scheduled_source,reason});try{return json(await serveReserve({s,origin,date,control,state,health,reason,eventType:"barb_originals_admin_hold"}),200,lab)}catch(e){return json({status:"SAFE_FALLBACK_REQUIRED",date_manila:date,scheduled_source:control.scheduled_source,served_source:null,source_health:health,error:e.message,message:"The scheduled source is on Admin hold and Barb Originals is unavailable. Do not serve institutional cached material while the hold is active."},503,lab)}}

  const refreshDue=Number(state?.refresh_due_at||0),fresh=state&&refreshDue>now&&Array.isArray(state.assets)&&state.assets.length,retryBlocked=health?.next_retry_at&&Date.parse(health.next_retry_at)>now,forceLiveResync=resync&&control.operating_mode==="LIVE_MIRROR";
  if(fresh&&!forceLiveResync){return json(responseRecord({date,control,served:state.served_source||control.scheduled_source,mode:state.service_mode||"primary",assets:state.assets,generation:state.generation||1,health,reason:state.fallback_reason||null,hold:!!state.hold_last_asset,cacheHit:true,refreshDueAt:refreshDue}),200,lab)}

  if(retryBlocked&&!forceFail){if(state&&Array.isArray(state.assets)&&state.assets.length){return json(responseRecord({date,control,served:state.served_source||control.scheduled_source,mode:state.service_mode||"same_source_cache",assets:state.assets,generation:state.generation||1,health,reason:state.fallback_reason||"Source retry is in backoff window",hold:!!state.hold_last_asset,cacheHit:true,refreshDueAt:refreshDue||Date.parse(health.next_retry_at)}),200,lab)}const cached=Array.isArray(lastGood?.assets)?lastGood.assets.slice(-Math.max(1,Math.min(control.batch_size,30))):[];if(cached.length)return json(responseRecord({date,control,served:control.scheduled_source,mode:"same_source_cache",assets:cached,generation:state?.generation||1,health,reason:"Source retry is in backoff window",hold:true,cacheHit:true,refreshDueAt:Date.parse(health.next_retry_at)}),200,lab);try{return json(await serveReserve({s,origin,date,control,state,health,reason:"Source retry is in backoff window and no same-source cache is available"}),200,lab)}catch{} }

  const seen=new Set((seenDoc?.ids||[]).map(String));let assets=[],error=null;
  if(!forceFail){for(let attempt=0;attempt<3&&assets.length<Math.min(6,control.batch_size);attempt++){try{const raw=await collectSource({adapterKey:control.adapter_key,sourceName:control.scheduled_source,origin,seed:hash(`${date}|${control.scheduled_source}|${state?.generation||0}|${attempt}|${Math.floor(now/(control.refresh_seconds*1000))}`),count:Math.max(control.batch_size*2,30)});assets=uniqueNew(raw,seen,control.batch_size);if(assets.length<Math.min(6,control.batch_size))throw new Error(`only ${assets.length} unseen eligible assets returned`)}catch(e){error=e;assets=[]}}}else error=new Error("diagnostic forced source failure");

  if(assets.length){const wasUnhealthy=health.state&&health.state!=="healthy",generation=(state?.generation||0)+1,nextRefresh=now+control.refresh_seconds*1000;health={state:"healthy",failures:0,next_retry_at:null,last_success_at:nowISO(),last_failure_at:health.last_failure_at||null};const merged=[],used=new Set();for(const x of [...(lastGood?.assets||[]),...assets]){if(!x?.id||used.has(String(x.id)))continue;used.add(String(x.id));merged.push(x)}lastGood={source:control.scheduled_source,updated_at:nowISO(),assets:merged.slice(-180)};state={scheduled_source:control.scheduled_source,served_source:control.scheduled_source,service_mode:"primary",generation,assets,refresh_due_at:nextRefresh,fallback_reason:null,hold_last_asset:false,updated_at:nowISO()};await Promise.all([s.setJSON(stateKey,state),s.setJSON(seenKey,{updated_at:nowISO(),ids:[...seen].slice(-5000)}),s.setJSON(cacheKey,lastGood),s.setJSON(healthKey,health)]);await event(s,date,wasUnhealthy?"source_recovered":"batch_refreshed",{scheduled_source:control.scheduled_source,generation,asset_count:assets.length,reason:forceLiveResync?"watchtower_live_resync":"scheduled_refresh"});const result=responseRecord({date,control,served:control.scheduled_source,mode:"primary",assets,generation,health,refreshDueAt:nextRefresh});await compatibility(s,result);return json(result,200,lab)}

  const failures=(Number(health.failures)||0)+1,backoff=BACKOFF_SECONDS[Math.min(failures-1,BACKOFF_SECONDS.length-1)],nextRetry=new Date(now+backoff*1000).toISOString(),firstFailure=health.state!=="degraded";health={state:"degraded",failures,next_retry_at:nextRetry,last_success_at:health.last_success_at||null,last_failure_at:nowISO(),last_error:clean(error?.message||"Source fetch failed")};await s.setJSON(healthKey,health);if(firstFailure)await event(s,date,"source_degraded",{scheduled_source:control.scheduled_source,error:health.last_error,next_retry_at:nextRetry});

  const cached=Array.isArray(lastGood?.assets)?lastGood.assets.slice(-Math.max(1,Math.min(control.batch_size,30))):[];
  if(cached.length){const generation=state?.generation||1,transition=state?.service_mode!=="same_source_cache";state={scheduled_source:control.scheduled_source,served_source:control.scheduled_source,service_mode:"same_source_cache",generation,assets:cached,refresh_due_at:Date.parse(nextRetry),fallback_reason:health.last_error,hold_last_asset:true,updated_at:nowISO()};await s.setJSON(stateKey,state);if(transition)await event(s,date,"same_source_cache_engaged",{scheduled_source:control.scheduled_source,error:health.last_error});const result=responseRecord({date,control,served:control.scheduled_source,mode:"same_source_cache",assets:cached,generation,health,reason:health.last_error,hold:true,refreshDueAt:Date.parse(nextRetry)});await compatibility(s,result);return json(result,200,lab)}

  try{return json(await serveReserve({s,origin,date,control,state,health,reason:health.last_error}),200,lab)}catch(e){error=new Error(`${health.last_error} | Barb Originals: ${e.message}`)}
  return json({status:"SAFE_FALLBACK_REQUIRED",date_manila:date,scheduled_source:control.scheduled_source,served_source:null,source_health:health,error:clean(error?.message||health.last_error),message:"No live source, no same-source cache, and no Barb Originals reserve asset is currently usable. The browser should keep the last successfully rendered asset on screen."},503,lab)
};
