const clean=v=>String(Array.isArray(v)?v[0]||"":v||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const asHttps=(v,base="")=>{try{const u=new URL(String(v||""),base||undefined);if(!/^https?:$/.test(u.protocol))return"";u.protocol="https:";return u.href}catch{return""}};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const out=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":status===200?"public, max-age=300, s-maxage=1800":"no-store"}});
async function getJSON(url,ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json","User-Agent":"BarbPH-Daily-Discover/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function getText(url,ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"text/html,*/*;q=.8","User-Agent":"BarbPH-Daily-Discover/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function imagesFromHTML(html,base,label,rights,seed){const items=[],seen=new Set();const tags=String(html).match(/<img\b[^>]*>/gi)||[];for(const tag of tags){const alt=clean(tag.match(/\balt=["']([^"']*)["']/i)?.[1]||"");const srcset=tag.match(/\bsrcset=["']([^"']+)["']/i)?.[1]||"";const src=tag.match(/\b(?:data-src|data-original|src)=["']([^"']+)["']/i)?.[1]||"";let candidate=src;if(srcset){const parts=srcset.split(",").map(x=>x.trim().split(/\s+/)[0]).filter(Boolean);candidate=parts.at(-1)||candidate}const image=asHttps(candidate,base);if(!image||seen.has(image)||/logo|icon|avatar|sprite|seal|favicon|placeholder|loading/i.test(image))continue;if(/copyright|all rights reserved|courtesy of (?!noaa|usgs)|shutterstock|getty images|istock/i.test(`${tag} ${alt}`))continue;if(/\b(person|people|man |woman |child|crew|staff|scientist|portrait)\b/i.test(alt))continue;seen.add(image);items.push({id:`${label.toLowerCase().replace(/\W+/g,"-")}:${hash(image)}`,title:alt||`${label} discovery`,creator:label,image,thumbnail:image,sourceURL:base,rightsLabel:rights})}if(items.length>1){const start=seed%items.length;return items.slice(start).concat(items.slice(0,start))}return items}

async function noaa(seed){const pages=[
"https://www.noaa.gov/noaa-collections/collections/photo-library/4617",
"https://www.noaa.gov/noaa-collections/collections/photo-library/4163",
"https://www.noaa.gov/noaa-collections/collections/photo-library/2327",
"https://www.noaa.gov/noaa-collections/collections/photo-library/2412",
"https://www.noaa.gov/noaa-collections/collections/photo-library"
];let all=[];for(let k=0;k<pages.length&&all.length<12;k++){const url=pages[(seed+k)%pages.length];try{const html=await getText(url);if(/verify you are human|captcha|access denied/i.test(html))continue;all.push(...imagesFromHTML(html,url,"NOAA","Public domain unless otherwise noted · NOAA",seed+k))}catch{}}const uniq=[...new Map(all.map(x=>[x.image,x])).values()];if(uniq.length<2)return out({error:"NOAA lab adapter reached the official gallery but could not extract two conservative image candidates. Keep this source parked until we refine the gallery parser."},503);return out({source:"NOAA",items:uniq.slice(0,12)});}

async function usgs(seed){const pages=[
"https://www.usgs.gov/products/multimedia-gallery/images",
`https://www.usgs.gov/products/multimedia-gallery/images?page=${seed%40}`,
"https://www.usgs.gov/3d-elevation-program/multimedia/images"
];let all=[];for(const url of pages){try{const html=await getText(url);all.push(...imagesFromHTML(html,url,"USGS","Public domain unless otherwise noted · USGS",seed))}catch{}}const uniq=[...new Map(all.map(x=>[x.image,x])).values()];if(uniq.length<2)return out({error:"USGS lab adapter could not extract two conservative image candidates from the official gallery. Keep this source parked until we refine the gallery parser."},503);return out({source:"USGS",items:uniq.slice(0,12)});}

async function nga(seed){const api=new URL("https://commons.wikimedia.org/w/api.php");api.searchParams.set("action","query");api.searchParams.set("format","json");api.searchParams.set("origin","*");api.searchParams.set("generator","search");api.searchParams.set("gsrsearch",'incategory:"Images from the National Gallery of Art"');api.searchParams.set("gsrnamespace","6");api.searchParams.set("gsrlimit","50");api.searchParams.set("gsroffset",String(seed%5000));api.searchParams.set("prop","imageinfo");api.searchParams.set("iiprop","url|extmetadata");api.searchParams.set("iiurlwidth","1600");let data;try{data=await getJSON(api)}catch(e){return out({error:`National Gallery adapter could not reach Wikimedia Commons (${e.message}).`},502)}const items=[];for(const p of Object.values(data?.query?.pages||{})){const ii=p?.imageinfo?.[0]||{},m=ii?.extmetadata||{},license=clean(m?.LicenseShortName?.value),usage=clean(m?.UsageTerms?.value);if(!/\bCC0\b/i.test(`${license} ${usage}`))continue;const image=asHttps(ii.thumburl||ii.url),id=String(p?.pageid||"");if(!image||!id)continue;items.push({id:`nga:${id}`,title:clean(m?.ObjectName?.value)||clean(m?.ImageDescription?.value)||clean(p?.title).replace(/^File:/,""),creator:clean(m?.Artist?.value)||"National Gallery of Art",image,thumbnail:asHttps(ii.thumburl),sourceURL:asHttps(ii.descriptionurl)||"https://www.nga.gov/",rightsLabel:"CC0 · National Gallery of Art"})}if(items.length<2)return out({error:"National Gallery adapter found fewer than two CC0 images in the official NGA Wikimedia collection for this seed."},503);return out({source:"National Gallery of Art",items});}

function walk(o,fn,depth=0){if(o==null||depth>9)return;if(Array.isArray(o)){for(const v of o)walk(v,fn,depth+1);return}if(typeof o!=="object")return;fn(o);for(const v of Object.values(o))walk(v,fn,depth+1)}
function gettyItem(record){let visual=null;walk(record,o=>{if(visual||o?.type!=="VisualItem")return;const ok=(o?.subject_to||[]).some(r=>(r?.classified_as||[]).some(c=>String(c?.id||"")==="https://creativecommons.org/publicdomain/zero/1.0/"));if(ok&&/^https:\/\/data\.getty\.edu\/media\/image\//.test(String(o?.id||"")))visual=o});if(!visual)return null;const imageId=String(visual.id).split("/").pop(),objectId=String(record?.id||""),title=clean(record?._label)||clean((record?.identified_by||[]).find(x=>x?.type==="Name")?.content)||"Getty Open Content artwork";let creator="J. Paul Getty Museum";const prod=(record?.produced_by?.carried_out_by||[])[0];if(prod?._label)creator=clean(prod._label);return{id:`getty:${imageId}`,title,creator,image:`https://media.getty.edu/iiif/image/${imageId}/full/1200,/0/default.jpg`,thumbnail:`https://media.getty.edu/iiif/image/${imageId}/full/600,/0/default.jpg`,sourceURL:objectId||"https://www.getty.edu/projects/open-content-program/",rightsLabel:"CC0 · Getty Open Content"}}
async function getty(seed){let root;try{root=await getJSON("https://data.getty.edu/museum/collection/activity-stream")}catch(e){return out({error:`Getty activity stream unavailable (${e.message}).`},502)}let pageURL=asHttps(root?.last?.id||root?.last);if(!pageURL)return out({error:"Getty activity stream did not expose a last page."},503);const candidates=[];for(let pageN=0;pageN<4&&pageURL&&candidates.length<50;pageN++){let page;try{page=await getJSON(pageURL)}catch{break}for(const a of page?.orderedItems||[]){const id=asHttps(a?.object?.id||a?.object);if(id&&/\/museum\/collection\/object\//.test(id))candidates.push(id)}pageURL=asHttps(page?.prev?.id||page?.prev)}const uniq=[...new Set(candidates)];if(!uniq.length)return out({error:"Getty activity stream returned no object records."},503);const start=seed%uniq.length,ordered=uniq.slice(start).concat(uniq.slice(0,start)),items=[];for(let i=0;i<ordered.length&&items.length<12;i+=5){const batch=await Promise.all(ordered.slice(i,i+5).map(u=>getJSON(u).catch(()=>null)));for(const r of batch){if(!r)continue;const x=gettyItem(r);if(x)items.push(x)}}if(items.length<2)return out({error:"Getty adapter found fewer than two CC0 Open Content images in the sampled records."},503);return out({source:"Getty Open Content",items});}

export default async request=>{if(request.method!=="GET")return out({error:"Method not allowed"},405);const u=new URL(request.url),source=(u.searchParams.get("source")||"").toLowerCase(),seed=Math.abs(parseInt(u.searchParams.get("seed")||"1",10)||1);try{if(source==="noaa")return await noaa(seed);if(source==="usgs")return await usgs(seed);if(source==="nga")return await nga(seed);if(source==="getty")return await getty(seed);return out({error:"Unknown open-world source."},400)}catch(e){return out({error:e?.message||"Open-world source failed."},502)}};