const clean=v=>String(Array.isArray(v)?v[0]||"":v||"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g," ").replace(/\s+/g," ").trim();
const asHttps=(v,base="")=>{try{const u=new URL(String(v||""),base||undefined);if(!/^https?:$/.test(u.protocol))return"";u.protocol="https:";return u.href}catch{return""}};
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const out=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":status===200?"public, max-age=300, s-maxage=1800":"no-store"}});
async function getJSON(url,ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/json","User-Agent":"BarbPH-Daily-Discover/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function getText(url,ms=14000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"text/html,*/*;q=.8","User-Agent":"BarbPH-Daily-Discover/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function imagesFromHTML(html,base,label,rights,seed){const items=[],seen=new Set();const tags=String(html).match(/<img\b[^>]*>/gi)||[];for(const tag of tags){const alt=clean(tag.match(/\balt=["']([^"']*)["']/i)?.[1]||"");const srcset=tag.match(/\bsrcset=["']([^"']+)["']/i)?.[1]||"";const src=tag.match(/\b(?:data-src|data-original|src)=["']([^"']+)["']/i)?.[1]||"";let candidate=src;if(srcset){const parts=srcset.split(",").map(x=>x.trim().split(/\s+/)[0]).filter(Boolean);candidate=parts.at(-1)||candidate}const image=asHttps(candidate,base);if(!image||seen.has(image)||/logo|icon|avatar|sprite|seal|favicon|placeholder|loading/i.test(image))continue;if(/copyright|all rights reserved|courtesy of (?!noaa|usgs)|shutterstock|getty images|istock/i.test(`${tag} ${alt}`))continue;if(/\b(person|people|man |woman |child|crew|staff|scientist|portrait)\b/i.test(alt))continue;seen.add(image);items.push({id:`${label.toLowerCase().replace(/\W+/g,"-")}:${hash(image)}`,title:alt||`${label} discovery`,creator:label,image,thumbnail:image,sourceURL:base,rightsLabel:rights})}if(items.length>1){const start=seed%items.length;return items.slice(start).concat(items.slice(0,start))}return items}

function htmlAttr(tag,name){const m=String(tag).match(new RegExp(`\\b${name}=["']([^"']+)["']`,`i`));return clean(m?.[1]||"")}
function metaValue(html,key){const tags=String(html).match(/<meta\b[^>]*>/gi)||[];for(const tag of tags){const prop=htmlAttr(tag,"property")||htmlAttr(tag,"name");if(prop.toLowerCase()===String(key).toLowerCase())return clean(htmlAttr(tag,"content"))}return""}
function noaaDetailLinks(html,base){const links=[];for(const tag of String(html).match(/<a\b[^>]*href=["'][^"']+["'][^>]*>/gi)||[]){const u=asHttps(htmlAttr(tag,"href"),base);if(!u)continue;try{const x=new URL(u);if(x.hostname!=="oceanexplorer.noaa.gov")continue;if(!x.pathname.startsWith("/multimedia/"))continue;if(x.pathname==="/multimedia/"||/\/(?:topics?|collections?|wallpapers?|videos?|images?)\/?$/i.test(x.pathname))continue;links.push(x.origin+x.pathname)}catch{}}return[...new Set(links)]}
function noaaItemFromPage(html,url){const plain=clean(html);const title=metaValue(html,"og:title")||clean(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||"")||"NOAA Ocean Exploration discovery";if(/\b(team|crew|scientist|researcher|person|people|portrait|student|staff|diver)\b/i.test(title))return null;const creditMatch=plain.match(/\bCredit\b\s*(.{0,700}?)(?:\bDownload\b|\bAvailable Downloads\b|\bRelated (?:Content|Expedition)\b|$)/i);const credit=clean(creditMatch?.[1]||"");if(/copyright|©|all rights reserved/i.test(credit))return null;const candidates=[];for(const m of String(html).matchAll(/<a\b[^>]*href=["']([^"']+\.(?:jpe?g|png|webp)(?:\?[^"']*)?)["'][^>]*>([\s\S]{0,220}?)<\/a>/gi)){const image=asHttps(m[1],url);if(!image||/logo|icon|seal|favicon|sprite|thumbnail/i.test(image))continue;const label=clean(m[2]);const score=(/largest|download|1920|full/i.test(label)?1000:0)+(/\.jpe?g(?:\?|$)/i.test(image)?100:0);candidates.push({image,score})}const og=asHttps(metaValue(html,"og:image"),url);if(og&&!/logo|icon|seal|favicon|sprite/i.test(og))candidates.push({image:og,score:100});candidates.sort((a,b)=>b.score-a.score);const image=candidates[0]?.image||"";if(!image)return null;const id=`noaa:${hash(url)}`;return{id,title,creator:credit||"NOAA Ocean Exploration",image,thumbnail:og||image,sourceURL:url,rightsLabel:"NOAA Ocean Exploration media guidance · no copyright notice in caption"}}
async function noaa(seed){
  const listings=[
    "https://oceanexplorer.noaa.gov/multimedia/",
    "https://oceanexplorer.noaa.gov/expedition-ex2503-multimedia/",
    "https://oceanexplorer.noaa.gov/expedition-ex2306-multimedia/",
    "https://oceanexplorer.noaa.gov/expedition-ex2604-multimedia/"
  ];
  const candidateLinks=[];
  for(const url of listings){try{const html=await getText(url,10000);candidateLinks.push(...noaaDetailLinks(html,url))}catch{}}
  const uniq=[...new Set(candidateLinks)];
  if(!uniq.length)return out({error:"NOAA Ocean Exploration listings were reachable but exposed no usable multimedia detail links. Keep this source parked."},503);
  const start=seed%uniq.length,ordered=uniq.slice(start).concat(uniq.slice(0,start)),items=[];
  for(let i=0;i<Math.min(ordered.length,30)&&items.length<12;i+=6){const batch=await Promise.all(ordered.slice(i,i+6).map(async u=>{try{return noaaItemFromPage(await getText(u,10000),u)}catch{return null}}));for(const x of batch){if(x&&!items.some(y=>y.id===x.id||y.image===x.image))items.push(x)}}
  if(items.length<2)return out({error:"NOAA Ocean Exploration was reached, but fewer than two non-copyrighted, non-people image candidates passed the conservative caption check. Keep this source parked and refine again."},503);
  return out({source:"NOAA",items:items.slice(0,12)});
}

async function usgs(seed){const pages=[
"https://www.usgs.gov/products/multimedia-gallery/images",
`https://www.usgs.gov/products/multimedia-gallery/images?page=${seed%40}`,
"https://www.usgs.gov/3d-elevation-program/multimedia/images"
];let all=[];for(const url of pages){try{const html=await getText(url);all.push(...imagesFromHTML(html,url,"USGS","Public domain unless otherwise noted · USGS",seed))}catch{}}const uniq=[...new Map(all.map(x=>[x.image,x])).values()];if(uniq.length<2)return out({error:"USGS lab adapter could not extract two conservative image candidates from the official gallery. Keep this source parked until we refine the gallery parser."},503);return out({source:"USGS",items:uniq.slice(0,12)});}

async function nga(seed){const api=new URL("https://commons.wikimedia.org/w/api.php");api.searchParams.set("action","query");api.searchParams.set("format","json");api.searchParams.set("origin","*");api.searchParams.set("generator","search");api.searchParams.set("gsrsearch",'incategory:"Images from the National Gallery of Art"');api.searchParams.set("gsrnamespace","6");api.searchParams.set("gsrlimit","50");api.searchParams.set("gsroffset",String(seed%5000));api.searchParams.set("prop","imageinfo");api.searchParams.set("iiprop","url|extmetadata");api.searchParams.set("iiurlwidth","1600");let data;try{data=await getJSON(api)}catch(e){return out({error:`National Gallery adapter could not reach Wikimedia Commons (${e.message}).`},502)}const items=[];for(const p of Object.values(data?.query?.pages||{})){const ii=p?.imageinfo?.[0]||{},m=ii?.extmetadata||{},license=clean(m?.LicenseShortName?.value),usage=clean(m?.UsageTerms?.value);if(!/\bCC0\b/i.test(`${license} ${usage}`))continue;const image=asHttps(ii.thumburl||ii.url),id=String(p?.pageid||"");if(!image||!id)continue;items.push({id:`nga:${id}`,title:clean(m?.ObjectName?.value)||clean(m?.ImageDescription?.value)||clean(p?.title).replace(/^File:/,""),creator:clean(m?.Artist?.value)||"National Gallery of Art",image,thumbnail:asHttps(ii.thumburl),sourceURL:asHttps(ii.descriptionurl)||"https://www.nga.gov/",rightsLabel:"CC0 · National Gallery of Art"})}if(items.length<2)return out({error:"National Gallery adapter found fewer than two CC0 images in the official NGA Wikimedia collection for this seed."},503);return out({source:"National Gallery of Art",items});}

function walk(o,fn,depth=0){if(o==null||depth>9)return;if(Array.isArray(o)){for(const v of o)walk(v,fn,depth+1);return}if(typeof o!=="object")return;fn(o);for(const v of Object.values(o))walk(v,fn,depth+1)}
function gettyMediaItem(record){if(!record||record?.type!=="VisualItem")return null;const id=asHttps(record?.id);if(!/^https:\/\/data\.getty\.edu\/media\/image\//.test(id))return null;const cc0=(record?.subject_to||[]).some(r=>(r?.classified_as||[]).some(c=>String(c?.id||"")==="https://creativecommons.org/publicdomain/zero/1.0/"));if(!cc0)return null;const imageId=id.split("/").pop();if(!imageId)return null;const title=clean(record?._label)||clean((record?.identified_by||[]).find(x=>x?.type==="Name")?.content)||"Getty Open Content image";return{id:`getty:${imageId}`,title,creator:"J. Paul Getty Museum",image:`https://media.getty.edu/iiif/image/${imageId}/full/1200,/0/default.jpg`,thumbnail:`https://media.getty.edu/iiif/image/${imageId}/full/600,/0/default.jpg`,sourceURL:id,rightsLabel:"CC0 · Getty Open Content"}}
function streamPageNumber(url){const m=String(url||"").match(/\/page\/(\d+)\/?$/);return m?Number(m[1]):0}
async function getty(seed){
  let root;try{root=await getJSON("https://data.getty.edu/media/activity-stream")}catch(e){return out({error:`Getty Media activity stream unavailable (${e.message}).`},502)}
  const lastURL=asHttps(root?.last?.id||root?.last),lastN=streamPageNumber(lastURL);
  if(!lastURL||!lastN)return out({error:"Getty Media activity stream did not expose a usable last page."},503);
  const pageNumbers=[];const span=Math.min(12000,Math.max(1,lastN-1));const offset=seed%span;
  for(let i=0;i<12;i++){const n=Math.max(1,lastN-((offset+i*997)%span));if(!pageNumbers.includes(n))pageNumbers.push(n)}
  const mediaURLs=[];
  for(const n of pageNumbers){let page;try{page=await getJSON(`https://data.getty.edu/media/activity-stream/page/${n}`,10000)}catch{continue}for(const a of page?.orderedItems||[]){const id=asHttps(a?.object?.id||a?.object);if(id&&/^https:\/\/data\.getty\.edu\/media\/image\//.test(id))mediaURLs.push(id)}if(mediaURLs.length>=80)break}
  const uniq=[...new Set(mediaURLs)];
  if(!uniq.length)return out({error:"Getty Media activity stream returned no VisualItem image records for the sampled pages."},503);
  const start=seed%uniq.length,ordered=uniq.slice(start).concat(uniq.slice(0,start)),items=[];
  for(let i=0;i<ordered.length&&items.length<12;i+=8){const batch=await Promise.all(ordered.slice(i,i+8).map(u=>getJSON(u,10000).catch(()=>null)));for(const r of batch){const x=gettyMediaItem(r);if(x&&!items.some(y=>y.id===x.id))items.push(x)}}
  if(items.length<2)return out({error:"Getty Media adapter sampled image records but found fewer than two with an explicit CC0 rights statement. Keep this source parked and refine again."},503);
  return out({source:"Getty Open Content",items:items.slice(0,12)});
}

export default async request=>{if(request.method!=="GET")return out({error:"Method not allowed"},405);const u=new URL(request.url),source=(u.searchParams.get("source")||"").toLowerCase(),seed=Math.abs(parseInt(u.searchParams.get("seed")||"1",10)||1);try{if(source==="noaa")return await noaa(seed);if(source==="usgs")return await usgs(seed);if(source==="nga")return await nga(seed);if(source==="getty")return await getty(seed);return out({error:"Unknown open-world source."},400)}catch(e){return out({error:e?.message||"Open-world source failed."},502)}};